# Site settings
title: Effy's Blog
email: effy.yin@gmail.com
description: dodo糯，Effy，前端开发
description1: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dodoroy.github.io" # the base hostname & protocol for your site
twitter_username: dodoroy
github_username:  dodoroy

# Build settings
markdown: kramdown
